import { Inject, Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { env, EventBusService, InternalHttpClient } from '@ethiopialearn/common';
import { courseCategoryLabel } from '@ethiopialearn/contracts';
import {
  AssessmentResultPayload,
  BulkPurchaseActivatedPayload,
  CourseProgressMilestonePayload,
  CourseUpdatedPayload,
  LearnerInactivePayload,
  PayRequestCreatedPayload,
  PaymentAbandonedPayload,
  ReferralInviteSentPayload,
  SponsorshipGrantedPayload,
  SponsorshipInvitedPayload,
  WalletCreditedPayload,
  CertificateIssuedPayload,
  CourseAppealSubmittedPayload,
  CourseInstitutionReviewedPayload,
  CourseReviewedPayload,
  CourseSubmittedToInstitutionPayload,
  CourseCompletedPayload,
  CoursePublishedPayload,
  CourseStatusPayload,
  CourseSubmittedPayload,
  EnrollmentCreatedPayload,
  FraudFlagPayload,
  InstructorLinkedPayload,
  PasswordResetRequestedPayload,
  PaymentConfirmedPayload,
  PaymentFailedPayload,
  PayoutPayload,
  QaDecisionAction,
  RefundDecisionPayload,
  RefundRequestedPayload,
  Role,
  StaffInvitedPayload,
  UserRegisteredPayload,
} from '@ethiopialearn/contracts';
import { EMAIL_PROVIDER, EmailProvider } from './email.provider';
import { InboxNotification, NotificationLog, NotificationPreference } from './entities';

function layout(title: string, bodyHtml: string): string {
  return `<div style="font-family:Arial,sans-serif;max-width:560px;margin:0 auto;padding:24px">
  <h2 style="color:#0f766e;margin-bottom:4px">EthiopiaLearn</h2>
  <h3 style="margin-top:0">${title}</h3>
  ${bodyHtml}
  <p style="color:#6b7280;font-size:12px;margin-top:32px">EthiopiaLearn · Addis Ababa, Ethiopia · This is a transactional email.</p>
</div>`;
}

interface InboxInput {
  user_id?: string | null;
  role?: string | null;
  type: string;
  title: string;
  body?: string;
  link?: string;
}

/**
 * The ONLY service that sends email (spec §0.5 rule 5), and the owner of the
 * in-app notification inbox. Subscribes to the full fanout exchange and reacts
 * with role-appropriate transactional email AND an in-app notification.
 */
@Injectable()
export class NotificationService implements OnModuleInit {
  private readonly logger = new Logger(NotificationService.name);
  private readonly adminEmail = env('PLATFORM_ADMIN_EMAIL', 'admin@ethiopialearn.et');
  private readonly webUrl = env('WEB_URL', 'http://localhost:3000');

  constructor(
    @InjectRepository(NotificationLog) private readonly log: Repository<NotificationLog>,
    @InjectRepository(InboxNotification) private readonly inboxRepo: Repository<InboxNotification>,
    @InjectRepository(NotificationPreference) private readonly prefs: Repository<NotificationPreference>,
    @Inject(EMAIL_PROVIDER) private readonly email: EmailProvider,
    private readonly bus: EventBusService,
    private readonly internal: InternalHttpClient,
  ) {}

  onModuleInit() {
    this.bus.subscribe<UserRegisteredPayload>('UserRegistered', (p) =>
      this.deliver('UserRegistered', p.user_id, p.email, 'Verify your EthiopiaLearn account',
        layout('Welcome to EthiopiaLearn!', `<p>Hi ${p.name},</p><p>Confirm your email address to activate your account:</p>
        <p><a href="${p.verification_url}" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Verify my email</a></p>
        <p>Or open this link: ${p.verification_url}</p><p>The link expires in 24 hours.</p>`)));

    this.bus.subscribe<PasswordResetRequestedPayload>('PasswordResetRequested', (p) =>
      this.deliver('PasswordResetRequested', p.user_id, p.email, 'Reset your EthiopiaLearn password',
        layout('Password reset', `<p>Hi ${p.name},</p><p>Use this link to set a new password (valid for 30 minutes):</p>
        <p><a href="${p.reset_url}">${p.reset_url}</a></p><p>If you didn't ask for this, ignore this email.</p>`)));

    // Staff / instructor invite — email a one-time link where they set their own
    // password. No password is ever generated by an admin or sent by email.
    this.bus.subscribe<StaffInvitedPayload>('StaffInvited', (p) =>
      this.deliver('StaffInvited', p.user_id, p.email, `You've been invited as ${p.role.replace('_', ' ')} on EthiopiaLearn`,
        layout('Set up your account', `<p>Hi ${p.name},</p><p>You've been invited to join EthiopiaLearn as a <strong>${p.role.replace('_', ' ')}</strong>.</p>
        <p>Click below to choose your password and get started — no temporary password needed:</p>
        <p><a href="${p.invite_url}" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Set my password</a></p>
        <p>Or open this link: ${p.invite_url}</p><p style="color:#6b7280;font-size:13px">This invitation expires in 7 days.</p>`)));

    // An existing account was added as an institution instructor.
    this.bus.subscribe<InstructorLinkedPayload>('InstructorLinked', (p) => {
      this.inbox({ user_id: p.user_id, type: 'instructor_added', title: `You're now an instructor at ${p.institution_name}`, body: p.upgraded_from_learner ? 'Your account was upgraded to educator — sign in again to open your teaching dashboard.' : 'New courses you create go through your institution’s review; your independent courses are unchanged.', link: '/teach' });
      this.deliver('InstructorLinked', p.user_id, p.email, `You're now an instructor at ${p.institution_name}`,
        layout('Welcome to the teaching team', `<p>Hi ${p.name},</p><p>You've been added as an instructor at <strong>${p.institution_name}</strong> on EthiopiaLearn.</p>
        ${p.upgraded_from_learner ? '<p>Your account has been upgraded so you can now create and manage courses — <strong>sign in again</strong> to see your teaching dashboard. Your existing enrollments and learning are unchanged.</p>' : '<p>New courses you create will go through your institution’s internal review; any courses you already own as an independent educator stay exactly as they are.</p>'}
        <p><a href="${this.webUrl}/teach" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Go to teaching dashboard</a></p>`));
    });

    // Course submitted → notify QOs in their queue (in-app; no email needed).
    this.bus.subscribe<CourseSubmittedPayload>('CourseSubmitted', (p) =>
      this.inbox({ role: Role.QUALITY_OFFICER, type: 'course_submitted', title: 'New course awaiting review', body: `"${p.title}" was submitted for quality review.`, link: '/qa' }));

    this.bus.subscribe<CourseAppealSubmittedPayload>('CourseAppealSubmitted', (p) =>
      this.inbox({ role: Role.QUALITY_OFFICER, type: 'course_appeal', title: 'Course appeal to review', body: `"${p.course_title}" was appealed: ${p.appeal_note.slice(0, 140)}`, link: '/qa' }));

    // Instructor submitted → notify the institution admin's internal review queue.
    this.bus.subscribe<CourseSubmittedToInstitutionPayload>('CourseSubmittedToInstitution', (p) =>
      this.inbox({ user_id: p.institution_admin_user_id, type: 'institution_review', title: 'Instructor course to review', body: `${p.instructor_name} submitted "${p.course_title}" for your review.`, link: '/institution/review' }));

    // Institution approved/rejected → notify the instructor.
    this.bus.subscribe<CourseInstitutionReviewedPayload>('CourseInstitutionReviewed', (p) =>
      this.inbox({
        user_id: p.owner_user_id,
        type: 'institution_decision',
        title: p.action === 'approve' ? 'Institution approved — forwarded to review' : 'Institution sent your course back',
        body: p.action === 'approve' ? `"${p.course_title}" was approved by your institution and sent to platform quality review.` : `"${p.course_title}" needs changes: ${p.notes ?? 'see your institution.'}`,
        link: `/teach/courses/${p.course_id}`,
      }));

    this.bus.subscribe<CourseReviewedPayload>('CourseReviewed', (p) => {
      const link = p.course_id ? `/teach/courses/${p.course_id}` : '/teach';
      if (p.action === QaDecisionAction.APPROVE) {
        this.inbox({ user_id: p.owner_user_id, type: 'course_approved', title: 'Your course is live! 🎉', body: `"${p.course_title}" passed review and is now published.`, link });
        if (p.owner_email) this.deliver('CourseReviewed', p.owner_user_id, p.owner_email, 'Your course is live!', layout('Your course is live! 🎉', `<p>"${p.course_title}" passed quality review and is now discoverable by learners.</p>`));
      } else if (p.action === QaDecisionAction.COACH) {
        this.inbox({ user_id: p.owner_user_id, type: 'course_coached', title: 'Feedback on your course', body: `"${p.course_title}": ${p.notes ?? 'changes requested'}`, link });
        if (p.owner_email) this.deliver('CourseReviewed', p.owner_user_id, p.owner_email, 'Feedback on your submitted course', layout('Feedback on your course', `<p>"${p.course_title}" needs some changes before it can go live:</p><blockquote>${p.notes ?? ''}</blockquote><p>The course is back in draft — update it and resubmit.</p>`));
      } else {
        this.inbox({ user_id: p.owner_user_id, type: 'course_flagged', title: 'Your course was flagged', body: `"${p.course_title}" was flagged. You can appeal from the course page.`, link });
        if (p.owner_email) this.deliver('CourseReviewed', p.owner_user_id, p.owner_email, 'Your course has been flagged', layout('Course flagged', `<p>"${p.course_title}" was flagged during review for a policy concern. You can submit an appeal from the course page.</p>`));
      }
    });

    this.bus.subscribe<CoursePublishedPayload>('CoursePublished', (p) => {
      // The instructor's own "your course is live" confirmation.
      this.inbox({ user_id: p.owner_user_id, type: 'course_published', title: 'Course published', body: `"${p.title}" is now live in the catalog.`, link: `/teach/courses/${p.course_id}` });
      // Fan out to learners who follow this category or this instructor.
      void this.notifyNewCourseFollowers(p);
    });

    this.bus.subscribe<PaymentConfirmedPayload>('PaymentConfirmed', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'payment_confirmed', title: 'Enrollment confirmed', body: `You now have access to "${p.course_title}".`, link: `/learn/${p.course_id}` });
      this.deliver('PaymentConfirmed', p.learner_id, p.learner_email, 'Enrollment confirmed — receipt',
        layout('Payment received', `<p>Hi ${p.learner_name},</p><p>Your payment of <strong>${p.amount_etb} ETB</strong> for "${p.course_title}" is confirmed. Your course is unlocked — happy learning!</p><p>Reference: ${p.tx_ref}</p>`));
    });

    this.bus.subscribe<PaymentFailedPayload>('PaymentFailed', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'payment_failed', title: 'Payment could not be processed', body: `Your payment for "${p.course_title}" did not go through.`, link: `/courses/${p.course_id}` });
      this.deliver('PaymentFailed', p.learner_id, p.learner_email, 'Your payment could not be processed',
        layout('Payment failed', `<p>Your payment for "${p.course_title}" (${p.amount_etb} ETB) did not go through. No money was taken for this attempt — you can retry from the course page.</p>`));
    });

    this.bus.subscribe<EnrollmentCreatedPayload>('EnrollmentCreated', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'enrolled', title: `You're enrolled: ${p.course_title}`, body: `Start learning "${p.course_title}" from your dashboard.`, link: `/learn/${p.course_id}` });
      this.deliver('EnrollmentCreated', p.learner_id, p.learner_email, `You're enrolled: ${p.course_title}`,
        layout('Enrollment confirmed', `<p>Hi ${p.learner_name},</p><p>You're enrolled in "${p.course_title}"${p.educator_name ? ` by ${p.educator_name}` : ''}. Start learning from your dashboard.</p>`));
    });

    this.bus.subscribe<CertificateIssuedPayload>('CertificateIssued', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'certificate', title: 'Your certificate is ready 🎓', body: `You completed "${p.course_title}".`, link: '/dashboard' });
      this.deliver('CertificateIssued', p.learner_id, p.learner_email, 'Your certificate is ready',
        layout('Certificate issued 🎓', `<p>Congratulations ${p.learner_name}!</p><p>You completed "${p.course_title}". Your certificate is available in your dashboard, and anyone can verify it here:</p><p><a href="${p.verify_url}">${p.verify_url}</a></p>`));
    });

    this.bus.subscribe<PayoutPayload>('PayoutCompleted', (p) => {
      this.inbox({ user_id: p.payee_id, type: 'payout', title: 'Payout sent', body: `${p.net_amount_etb} ETB was disbursed to your account.`, link: '/teach' });
      if (p.payee_email) this.deliver('PayoutCompleted', p.payee_id, p.payee_email, 'Payout sent to your account',
        layout('Payout completed', `<p>Your payout of <strong>${p.net_amount_etb} ETB</strong> (gross ${p.gross_amount_etb} ETB − platform fee ${p.platform_fee_etb} ETB) has been disbursed.</p>`));
    });

    this.bus.subscribe<FraudFlagPayload>('FraudFlagRaised', (p) => {
      this.inbox({ role: Role.PLATFORM_ADMIN, type: 'fraud', title: 'Fraud flag raised', body: `${p.signal_type} on ${p.subject_type}. ${p.detail}`, link: '/admin' });
      this.deliver('FraudFlagRaised', null, this.adminEmail, 'Fraud flag raised — action needed',
        layout('Fraud flag raised', `<p>Signal <strong>${p.signal_type}</strong> on ${p.subject_type} <code>${p.subject_id}</code>.</p><p>${p.detail}</p><p>Payouts for the related payee are on hold until resolved in the admin console.</p>`));
    });

    this.bus.subscribe<FraudFlagPayload>('FraudFlagResolved', (p) =>
      this.deliver('FraudFlagResolved', null, this.adminEmail, 'Fraud flag resolved',
        layout('Fraud flag resolved', `<p>Flag <code>${p.flag_id}</code> (${p.signal_type}) has been resolved. Any payout holds have been released.</p>`)));

    // A refund needs an admin decision (manual-review band) → actionable admin inbox.
    this.bus.subscribe<RefundRequestedPayload>('RefundRequested', (p) => {
      this.inbox({ role: Role.PLATFORM_ADMIN, type: 'refund_request', title: 'Refund awaiting your decision', body: `${p.amount_etb} ETB refund requested for "${p.course_title}" (${p.reason}).`, link: '/admin' });
      this.deliver('RefundRequested', null, this.adminEmail, 'Refund request awaiting review',
        layout('Refund awaiting decision', `<p>A learner requested a ${p.amount_etb} ETB refund for "${p.course_title}".</p><p>Routing rule: <code>${p.reason}</code>. Approve or deny it in the admin console.</p>`));
    });

    this.bus.subscribe<RefundDecisionPayload>('RefundApproved', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'refund', title: 'Refund processed', body: `Your refund for "${p.course_title}" was approved.`, link: '/dashboard' });
      // Also record it in the admin inbox — many approvals are automatic (spec §10.4)
      // and never crossed an admin's desk, but they still move money.
      this.inbox({ role: Role.PLATFORM_ADMIN, type: 'refund', title: 'Refund approved', body: `${p.amount_etb} ETB refunded for "${p.course_title}".`, link: '/admin' });
      this.deliver('RefundApproved', p.learner_id, p.learner_email, 'Your refund has been processed',
        layout('Refund processed', `<p>Your refund of ${p.amount_etb} ETB for "${p.course_title}" was approved. Access to the course has been revoked.</p>`));
    });

    this.bus.subscribe<RefundDecisionPayload>('RefundDenied', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'refund', title: 'Refund request declined', body: `Your refund for "${p.course_title}" was declined (${p.reason}).`, link: '/dashboard' });
      this.deliver('RefundDenied', p.learner_id, p.learner_email, 'Refund request decision',
        layout('Refund request declined', `<p>Your refund request for "${p.course_title}" was declined (${p.reason}). Reply to this email if you believe this is a mistake.</p>`));
    });

    this.bus.subscribe<CourseCompletedPayload>('CourseCompleted', (p) =>
      this.deliver('CourseCompleted', p.learner_id, p.learner_email, `You finished ${p.course_title}!`,
        layout('Course completed', `<p>Well done ${p.learner_name} — you finished every lesson in "${p.course_title}".</p>`)));

    this.bus.subscribe<AssessmentResultPayload>('AssessmentFailed', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'assessment', title: 'Assessment not passed', body: `Your ${p.assessment_type} for "${p.course_title}" scored ${p.score}.`, link: `/learn/${p.course_id}` });
      this.deliver('AssessmentFailed', p.learner_id, p.learner_email, 'Assessment result',
        layout('Assessment not passed', `<p>Your ${p.assessment_type} attempt for "${p.course_title}" scored ${p.score}. You can try again from the course page.</p>`));
    });

    // ---- Growth & commerce ----

    this.bus.subscribe<SponsorshipGrantedPayload>('SponsorshipGranted', async (p) => {
      const what = p.source === 'bulk' ? `${p.organization_name || p.sponsor_name} enrolled you in` : p.source === 'gift' ? `${p.sponsor_name || 'Someone'} gifted you` : `${p.sponsor_name || 'Someone'} paid for`;
      this.inbox({ user_id: p.recipient_user_id, type: 'gift', title: `🎁 ${what} "${p.course_title}"`, body: p.message || 'The course is unlocked — start learning from your dashboard.', link: `/learn/${p.course_id}` });
      if (p.sponsor_id) {
        this.inbox({ user_id: p.sponsor_id, type: 'gift_delivered', title: `Delivered: "${p.course_title}"`, body: `${p.recipient_email} now has access. Follow their progress from your dashboard.`, link: '/dashboard' });
      }
      const user = await this.userInfo(p.recipient_user_id);
      const to = user.email || p.recipient_email;
      if (to) this.deliver('SponsorshipGranted', p.recipient_user_id, to, `${what} a course on EthiopiaLearn`,
        layout('A course was unlocked for you 🎁', `<p>Hi ${user.name || 'there'},</p><p>${what} <strong>"${p.course_title}"</strong>.</p>${p.message ? `<blockquote style="border-left:3px solid #0f766e;margin:12px 0;padding:6px 12px;color:#374151">${p.message}</blockquote>` : ''}<p><a href="${this.webUrl}/learn/${p.course_id}" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Start learning</a></p>`));
    });

    this.bus.subscribe<SponsorshipInvitedPayload>('SponsorshipInvited', (p) => {
      const who = p.source === 'bulk' ? (p.organization_name || p.sponsor_name) : p.sponsor_name || 'Someone';
      this.deliver('SponsorshipInvited', null, p.recipient_email, `${who} has enrolled you in "${p.course_title}"`,
        layout('You have a course waiting 🎁', `<p>${who} bought <strong>"${p.course_title}"</strong> on EthiopiaLearn for you.</p>${p.message ? `<blockquote style="border-left:3px solid #0f766e;margin:12px 0;padding:6px 12px;color:#374151">${p.message}</blockquote>` : ''}<p>Create a free account with <strong>this email address</strong> and the course unlocks automatically:</p><p><a href="${p.signup_url}" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Create my account</a></p><p style="color:#6b7280;font-size:12px">Or open: ${p.signup_url}</p>`));
    });

    this.bus.subscribe<PayRequestCreatedPayload>('PayRequestCreated', (p) => {
      this.inbox({ user_id: p.requester_id, type: 'pay_request', title: 'Payment request sent', body: `We emailed ${p.payer_email} asking them to pay for "${p.course_title}".`, link: '/dashboard' });
      this.deliver('PayRequestCreated', null, p.payer_email, `${p.requester_name} is asking you to pay for a course`,
        layout(`${p.requester_name} needs your help 🙏`, `<p><strong>${p.requester_name}</strong> would like to take <strong>"${p.course_title}"</strong> on EthiopiaLearn (${p.amount_etb} ETB) and is asking you to cover it.</p>${p.message ? `<blockquote style="border-left:3px solid #0f766e;margin:12px 0;padding:6px 12px;color:#374151">${p.message}</blockquote>` : ''}<p><a href="${p.pay_url}" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">View the course &amp; pay</a></p><p style="color:#6b7280;font-size:12px">You pay securely with Chapa (Telebirr, CBE Birr and 18+ banks). ${p.requester_name} gets access the moment it clears.</p>`));
    });

    this.bus.subscribe<ReferralInviteSentPayload>('ReferralInviteSent', (p) => {
      const cta = p.existing_user ? `<p>You already have an account — <a href="${this.webUrl}/login">log in</a> and browse the catalog.</p>` : `<p><a href="${p.signup_url}" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Join EthiopiaLearn</a></p><p style="color:#6b7280;font-size:12px">Or open: ${p.signup_url}</p>`;
      this.deliver('ReferralInviteSent', null, p.to_email, `${p.referrer_name} invited you to EthiopiaLearn`,
        layout(`${p.referrer_name} thinks you'd like this`, `<p><strong>${p.referrer_name}</strong> invited you to ${p.role_hint === 'educator' ? 'teach on' : 'learn on'} EthiopiaLearn — real skills from Ethiopian experts, verifiable certificates, pay with Telebirr or any Ethiopian bank.</p>${p.message ? `<blockquote style="border-left:3px solid #0f766e;margin:12px 0;padding:6px 12px;color:#374151">${p.message}</blockquote>` : ''}${cta}`));
    });

    this.bus.subscribe<PaymentAbandonedPayload>('PaymentAbandoned', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'abandoned_cart', title: `Still want "${p.course_title}"?`, body: `Your checkout didn't complete. Your place is waiting — finish in one tap.`, link: `/courses/${p.course_id}` });
      if (p.learner_email) this.deliver('PaymentAbandoned', p.learner_id, p.learner_email, `Finish enrolling in "${p.course_title}"`,
        layout('Your course is waiting', `<p>Hi ${p.learner_name || 'there'},</p><p>You started enrolling in <strong>"${p.course_title}"</strong> (${p.amount_etb} ETB) but the payment didn't complete. No money was taken.</p><p><a href="${p.resume_url}" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Finish enrolling</a></p><p style="color:#6b7280;font-size:12px">Not interested any more? Just ignore this — we won't remind you again.</p>`));
    });

    this.bus.subscribe<WalletCreditedPayload>('WalletCredited', (p) => {
      const title = p.kind === 'referral_reward' ? `You earned ${p.amount_etb} ETB 🎉` : p.kind === 'cashback' ? `${p.amount_etb} ETB cashback added` : `${p.amount_etb} ETB added to your wallet`;
      this.inbox({ user_id: p.user_id, type: 'wallet', title, body: `${p.note}. Balance: ${p.balance_etb} ETB — spend it on any course.`, link: '/dashboard' });
    });

    this.bus.subscribe<BulkPurchaseActivatedPayload>('BulkPurchaseActivated', (p) => {
      this.inbox({ user_id: p.buyer_id, type: 'bulk', title: `${p.seats} seats ready: "${p.course_title}"`, body: 'Assign seats to your team by email from the Institution page.', link: '/institution' });
      if (p.buyer_email) this.deliver('BulkPurchaseActivated', p.buyer_id, p.buyer_email, `Your ${p.seats} seats for "${p.course_title}" are ready`,
        layout('Bulk purchase confirmed', `<p>Payment of <strong>${p.total_etb} ETB</strong> for <strong>${p.seats} seats</strong> of "${p.course_title}" (${p.organization_name}) is confirmed.</p><p>Assign seats by entering your team's email addresses — people with an account get instant access, everyone else gets an invitation that unlocks the course when they sign up.</p><p><a href="${this.webUrl}/institution" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Assign seats</a></p>`));
    });

    // ---- Engagement ----

    this.bus.subscribe<CourseUpdatedPayload>('CourseUpdated', (p) => void this.notifyCourseUpdated(p));

    this.bus.subscribe<CourseProgressMilestonePayload>('CourseProgressMilestone', async (p) => {
      const cheer = p.percent === 25 ? 'Great start' : p.percent === 50 ? 'Halfway there' : 'Almost done';
      this.inbox({ user_id: p.learner_id, type: 'progress', title: `${cheer} — ${p.percent}% of "${p.course_title}"`, body: p.percent === 75 ? 'Finish the last lessons to earn your certificate.' : 'Keep the momentum going.', link: `/learn/${p.course_id}` });
      if (p.percent >= 50) {
        const pref = await this.prefs.findOne({ where: { user_id: p.learner_id } });
        if (pref?.progress_emails === false) return;
        const user = await this.userInfo(p.learner_id);
        const to = p.learner_email || user.email;
        if (to) this.deliver('CourseProgressMilestone', p.learner_id, to, `${cheer}! You're ${p.percent}% through "${p.course_title}"`,
          layout(`${cheer} 🚀`, `<p>Hi ${user.name || 'there'},</p><p>You've completed <strong>${p.percent}%</strong> of "${p.course_title}".${p.percent === 75 ? ' A few more lessons and your verifiable certificate is yours.' : ''}</p><p><a href="${this.webUrl}/learn/${p.course_id}" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Continue learning</a></p>`));
      }
    });

    this.bus.subscribe<LearnerInactivePayload>('LearnerInactive', async (p) => {
      if (p.channel === 'in_app') {
        this.inbox({ user_id: p.learner_id, type: 'inactive', title: `Pick up "${p.course_title}" where you left off`, body: `It's been ${p.days_inactive} days. You're ${p.progress_percent}% through — a short lesson today keeps it going.`, link: `/learn/${p.course_id}` });
        return;
      }
      const pref = await this.prefs.findOne({ where: { user_id: p.learner_id } });
      if (pref?.inactivity_emails === false || pref?.marketing_opt_out) return;
      const user = await this.userInfo(p.learner_id);
      if (!user.email) return;
      this.deliver('LearnerInactive', p.learner_id, user.email, `We miss you in "${p.course_title}"`,
        layout('Your course is still here', `<p>Hi ${user.name || 'there'},</p><p>It's been ${p.days_inactive} days since you last studied <strong>"${p.course_title}"</strong>. You're already <strong>${p.progress_percent}%</strong> through — pick a lesson and keep going.</p><p><a href="${this.webUrl}/learn/${p.course_id}" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Resume the course</a></p><p style="color:#6b7280;font-size:12px">You can turn these reminders off in Account → Notification preferences.</p>`));
    });

    this.bus.subscribe<CourseStatusPayload>('CourseUnlisted', (p) => {
      this.inbox({ user_id: p.owner_user_id, type: 'course_unlisted', title: 'Your course was unlisted', body: `"${p.title}" was removed from the catalog.`, link: `/teach/courses/${p.course_id}` });
      if (p.owner_email) this.deliver('CourseUnlisted', p.owner_user_id, p.owner_email, 'Your course was unlisted',
        layout('Course unlisted', `<p>"${p.title}" was temporarily removed from the catalog. You can re-publish it from your course page (or contact us if an admin unlisted it).</p>`));
    });
  }

  /**
   * When a course is published, notify every learner who follows its category
   * or its instructor — in-app and/or email, per each learner's preferences.
   * Best-effort: a failure for one recipient never blocks the others.
   */
  private async notifyNewCourseFollowers(p: CoursePublishedPayload) {
    let followers: NotificationPreference[];
    try {
      followers = await this.prefs
        .createQueryBuilder('pref')
        .where('(:category = ANY(pref.new_course_categories)) OR (:owner = ANY(pref.new_course_instructor_ids))', {
          category: p.category,
          owner: p.owner_user_id,
        })
        .limit(2000) // safety cap; batch/queue this if follower counts ever get huge
        .getMany();
    } catch (err) {
      this.logger.warn(`new-course fan-out query failed for ${p.course_id}: ${(err as Error).message}`);
      return;
    }
    // Don't notify the instructor about their own course (they get the owner ping).
    followers = followers.filter((f) => f.user_id !== p.owner_user_id);
    if (followers.length === 0) return;

    const instructorName = await this.userName(p.owner_user_id);
    const categoryLabel = courseCategoryLabel(p.category);
    const link = `/courses/${p.course_id}`;
    this.logger.log(`CoursePublished "${p.title}" → notifying ${followers.length} follower(s)`);

    for (const f of followers) {
      const followsInstructor = (f.new_course_instructor_ids ?? []).includes(p.owner_user_id);
      const reason = followsInstructor ? `${instructorName} just published a new course` : `New ${categoryLabel} course`;
      if (f.new_course_in_app !== false) {
        await this.inbox({ user_id: f.user_id, type: 'new_course', title: reason, body: `"${p.title}" is now available. Tap to explore.`, link });
      }
      if (f.new_course_email !== false) {
        const user = await this.userInfo(f.user_id);
        if (!user.email) continue;
        await this.deliver('NewCourseAlert', f.user_id, user.email, `${reason}: ${p.title}`,
          layout(reason, `<p>Hi ${user.name || 'there'},</p>
          <p>${followsInstructor ? `<strong>${instructorName}</strong> just published` : `A new <strong>${categoryLabel}</strong> course just dropped`} on EthiopiaLearn:</p>
          <p style="font-size:16px"><strong>${p.title}</strong></p>
          <p><a href="${this.webUrl}${link}" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">View the course</a></p>
          <p style="color:#6b7280;font-size:12px;margin-top:16px">You're getting this because you follow ${followsInstructor ? 'this instructor' : `the ${categoryLabel} category`}. Manage alerts in your account settings.</p>`));
      }
    }
  }

  /** Major course update → every active learner gets an inbox item, and an email unless they opted out. */
  private async notifyCourseUpdated(p: CourseUpdatedPayload) {
    let learnerIds: string[] = [];
    try {
      learnerIds = (await this.internal.get<{ learner_ids: string[] }>(`/api/v1/internal/courses/${p.course_id}/learners`)).learner_ids;
    } catch (err) {
      this.logger.warn(`course-updated fan-out: could not list learners for ${p.course_id}: ${(err as Error).message}`);
      return;
    }
    learnerIds = learnerIds.filter((id) => id !== p.owner_user_id).slice(0, 5000);
    if (!learnerIds.length) return;
    this.logger.log(`CourseUpdated "${p.course_title}" → ${learnerIds.length} learner(s)`);
    for (const learnerId of learnerIds) {
      await this.inbox({ user_id: learnerId, type: 'course_updated', title: `Updated: "${p.course_title}"`, body: p.summary, link: `/learn/${p.course_id}?changelog=1` });
      const pref = await this.prefs.findOne({ where: { user_id: learnerId } });
      if (pref?.course_updates_email === false) continue;
      const user = await this.userInfo(learnerId);
      if (!user.email) continue;
      await this.deliver('CourseUpdated', learnerId, user.email, `"${p.course_title}" has new content`,
        layout('Your course was updated', `<p>Hi ${user.name || 'there'},</p><p>The instructor updated <strong>"${p.course_title}"</strong>:</p><blockquote style="border-left:3px solid #0f766e;margin:12px 0;padding:6px 12px;color:#374151">${p.summary}</blockquote><p><a href="${this.webUrl}/learn/${p.course_id}?changelog=1" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">See what changed</a></p>`));
    }
  }

  private async userInfo(userId: string): Promise<{ email: string; name: string }> {
    try {
      return await this.internal.get<{ email: string; name: string }>(`/api/v1/internal/users/${userId}`);
    } catch {
      return { email: '', name: '' };
    }
  }

  private async userName(userId: string): Promise<string> {
    return (await this.userInfo(userId)).name || 'An instructor you follow';
  }

  private async inbox(input: InboxInput) {
    if (!input.user_id && !input.role) return;
    try {
      await this.inboxRepo.save(
        this.inboxRepo.create({
          user_id: input.user_id ?? null,
          target_role: input.role ?? null,
          type: input.type,
          title: input.title,
          body: input.body ?? '',
          link: input.link ?? null,
          read_at: null,
        }),
      );
    } catch (err) {
      this.logger.warn(`inbox write failed (${input.type}): ${(err as Error).message}`);
    }
  }

  private async deliver(eventType: string, userId: string | null, to: string, subject: string, html: string) {
    if (!to) {
      this.logger.warn(`skipping ${eventType}: no recipient`);
      return;
    }
    try {
      const { message_id } = await this.email.send({ to, subject, html });
      await this.log.save(
        this.log.create({ user_id: userId, event_type: eventType, channel: 'email', recipient: to, subject, status: 'sent', provider_message_id: message_id }),
      );
      await this.bus.publish('NotificationSent', { user_id: userId, event_type: eventType, channel: 'email' });
    } catch (err) {
      this.logger.error(`email failed for ${eventType} -> ${to}: ${(err as Error).message}`);
      await this.log.save(
        this.log.create({ user_id: userId, event_type: eventType, channel: 'email', recipient: to, subject, status: 'failed', provider_message_id: null }),
      );
    }
  }
}
