import { Inject, Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { env, EventBusService, InternalHttpClient } from '@ethiopialearn/common';
import { courseCategoryLabel } from '@ethiopialearn/contracts';
import {
  AssessmentResultPayload,
  CertificateIssuedPayload,
  CourseAppealSubmittedPayload,
  CourseInstitutionReviewedPayload,
  CourseReviewedPayload,
  CourseSubmittedToInstitutionPayload,
  CourseCompletedPayload,
  CoursePublishedPayload,
  CourseStatusPayload,
  CourseSubmittedPayload,
  EnrollmentCreatedPayload,
  FraudFlagPayload,
  InstructorLinkedPayload,
  PasswordResetRequestedPayload,
  PaymentConfirmedPayload,
  PaymentFailedPayload,
  PayoutPayload,
  QaDecisionAction,
  RefundDecisionPayload,
  RefundRequestedPayload,
  Role,
  StaffInvitedPayload,
  UserRegisteredPayload,
} from '@ethiopialearn/contracts';
import { EMAIL_PROVIDER, EmailProvider } from './email.provider';
import { InboxNotification, NotificationLog, NotificationPreference } from './entities';

function layout(title: string, bodyHtml: string): string {
  return `<div style="font-family:Arial,sans-serif;max-width:560px;margin:0 auto;padding:24px">
  <h2 style="color:#0f766e;margin-bottom:4px">EthiopiaLearn</h2>
  <h3 style="margin-top:0">${title}</h3>
  ${bodyHtml}
  <p style="color:#6b7280;font-size:12px;margin-top:32px">EthiopiaLearn · Addis Ababa, Ethiopia · This is a transactional email.</p>
</div>`;
}

interface InboxInput {
  user_id?: string | null;
  role?: string | null;
  type: string;
  title: string;
  body?: string;
  link?: string;
}

/**
 * The ONLY service that sends email (spec §0.5 rule 5), and the owner of the
 * in-app notification inbox. Subscribes to the full fanout exchange and reacts
 * with role-appropriate transactional email AND an in-app notification.
 */
@Injectable()
export class NotificationService implements OnModuleInit {
  private readonly logger = new Logger(NotificationService.name);
  private readonly adminEmail = env('PLATFORM_ADMIN_EMAIL', 'admin@ethiopialearn.et');
  private readonly webUrl = env('WEB_URL', 'http://localhost:3000');

  constructor(
    @InjectRepository(NotificationLog) private readonly log: Repository<NotificationLog>,
    @InjectRepository(InboxNotification) private readonly inboxRepo: Repository<InboxNotification>,
    @InjectRepository(NotificationPreference) private readonly prefs: Repository<NotificationPreference>,
    @Inject(EMAIL_PROVIDER) private readonly email: EmailProvider,
    private readonly bus: EventBusService,
    private readonly internal: InternalHttpClient,
  ) {}

  onModuleInit() {
    this.bus.subscribe<UserRegisteredPayload>('UserRegistered', (p) =>
      this.deliver('UserRegistered', p.user_id, p.email, 'Verify your EthiopiaLearn account',
        layout('Welcome to EthiopiaLearn!', `<p>Hi ${p.name},</p><p>Confirm your email address to activate your account:</p>
        <p><a href="${p.verification_url}" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Verify my email</a></p>
        <p>Or open this link: ${p.verification_url}</p><p>The link expires in 24 hours.</p>`)));

    this.bus.subscribe<PasswordResetRequestedPayload>('PasswordResetRequested', (p) =>
      this.deliver('PasswordResetRequested', p.user_id, p.email, 'Reset your EthiopiaLearn password',
        layout('Password reset', `<p>Hi ${p.name},</p><p>Use this link to set a new password (valid for 30 minutes):</p>
        <p><a href="${p.reset_url}">${p.reset_url}</a></p><p>If you didn't ask for this, ignore this email.</p>`)));

    // Staff / instructor invite — email a one-time link where they set their own
    // password. No password is ever generated by an admin or sent by email.
    this.bus.subscribe<StaffInvitedPayload>('StaffInvited', (p) =>
      this.deliver('StaffInvited', p.user_id, p.email, `You've been invited as ${p.role.replace('_', ' ')} on EthiopiaLearn`,
        layout('Set up your account', `<p>Hi ${p.name},</p><p>You've been invited to join EthiopiaLearn as a <strong>${p.role.replace('_', ' ')}</strong>.</p>
        <p>Click below to choose your password and get started — no temporary password needed:</p>
        <p><a href="${p.invite_url}" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Set my password</a></p>
        <p>Or open this link: ${p.invite_url}</p><p style="color:#6b7280;font-size:13px">This invitation expires in 7 days.</p>`)));

    // An existing account was added as an institution instructor.
    this.bus.subscribe<InstructorLinkedPayload>('InstructorLinked', (p) => {
      this.inbox({ user_id: p.user_id, type: 'instructor_added', title: `You're now an instructor at ${p.institution_name}`, body: p.upgraded_from_learner ? 'Your account was upgraded to educator — sign in again to open your teaching dashboard.' : 'New courses you create go through your institution’s review; your independent courses are unchanged.', link: '/teach' });
      this.deliver('InstructorLinked', p.user_id, p.email, `You're now an instructor at ${p.institution_name}`,
        layout('Welcome to the teaching team', `<p>Hi ${p.name},</p><p>You've been added as an instructor at <strong>${p.institution_name}</strong> on EthiopiaLearn.</p>
        ${p.upgraded_from_learner ? '<p>Your account has been upgraded so you can now create and manage courses — <strong>sign in again</strong> to see your teaching dashboard. Your existing enrollments and learning are unchanged.</p>' : '<p>New courses you create will go through your institution’s internal review; any courses you already own as an independent educator stay exactly as they are.</p>'}
        <p><a href="${this.webUrl}/teach" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Go to teaching dashboard</a></p>`));
    });

    // Course submitted → notify QOs in their queue (in-app; no email needed).
    this.bus.subscribe<CourseSubmittedPayload>('CourseSubmitted', (p) =>
      this.inbox({ role: Role.QUALITY_OFFICER, type: 'course_submitted', title: 'New course awaiting review', body: `"${p.title}" was submitted for quality review.`, link: '/qa' }));

    this.bus.subscribe<CourseAppealSubmittedPayload>('CourseAppealSubmitted', (p) =>
      this.inbox({ role: Role.QUALITY_OFFICER, type: 'course_appeal', title: 'Course appeal to review', body: `"${p.course_title}" was appealed: ${p.appeal_note.slice(0, 140)}`, link: '/qa' }));

    // Instructor submitted → notify the institution admin's internal review queue.
    this.bus.subscribe<CourseSubmittedToInstitutionPayload>('CourseSubmittedToInstitution', (p) =>
      this.inbox({ user_id: p.institution_admin_user_id, type: 'institution_review', title: 'Instructor course to review', body: `${p.instructor_name} submitted "${p.course_title}" for your review.`, link: '/institution/review' }));

    // Institution approved/rejected → notify the instructor.
    this.bus.subscribe<CourseInstitutionReviewedPayload>('CourseInstitutionReviewed', (p) =>
      this.inbox({
        user_id: p.owner_user_id,
        type: 'institution_decision',
        title: p.action === 'approve' ? 'Institution approved — forwarded to review' : 'Institution sent your course back',
        body: p.action === 'approve' ? `"${p.course_title}" was approved by your institution and sent to platform quality review.` : `"${p.course_title}" needs changes: ${p.notes ?? 'see your institution.'}`,
        link: `/teach/courses/${p.course_id}`,
      }));

    this.bus.subscribe<CourseReviewedPayload>('CourseReviewed', (p) => {
      const link = p.course_id ? `/teach/courses/${p.course_id}` : '/teach';
      if (p.action === QaDecisionAction.APPROVE) {
        this.inbox({ user_id: p.owner_user_id, type: 'course_approved', title: 'Your course is live! 🎉', body: `"${p.course_title}" passed review and is now published.`, link });
        if (p.owner_email) this.deliver('CourseReviewed', p.owner_user_id, p.owner_email, 'Your course is live!', layout('Your course is live! 🎉', `<p>"${p.course_title}" passed quality review and is now discoverable by learners.</p>`));
      } else if (p.action === QaDecisionAction.COACH) {
        this.inbox({ user_id: p.owner_user_id, type: 'course_coached', title: 'Feedback on your course', body: `"${p.course_title}": ${p.notes ?? 'changes requested'}`, link });
        if (p.owner_email) this.deliver('CourseReviewed', p.owner_user_id, p.owner_email, 'Feedback on your submitted course', layout('Feedback on your course', `<p>"${p.course_title}" needs some changes before it can go live:</p><blockquote>${p.notes ?? ''}</blockquote><p>The course is back in draft — update it and resubmit.</p>`));
      } else {
        this.inbox({ user_id: p.owner_user_id, type: 'course_flagged', title: 'Your course was flagged', body: `"${p.course_title}" was flagged. You can appeal from the course page.`, link });
        if (p.owner_email) this.deliver('CourseReviewed', p.owner_user_id, p.owner_email, 'Your course has been flagged', layout('Course flagged', `<p>"${p.course_title}" was flagged during review for a policy concern. You can submit an appeal from the course page.</p>`));
      }
    });

    this.bus.subscribe<CoursePublishedPayload>('CoursePublished', (p) => {
      // The instructor's own "your course is live" confirmation.
      this.inbox({ user_id: p.owner_user_id, type: 'course_published', title: 'Course published', body: `"${p.title}" is now live in the catalog.`, link: `/teach/courses/${p.course_id}` });
      // Fan out to learners who follow this category or this instructor.
      void this.notifyNewCourseFollowers(p);
    });

    this.bus.subscribe<PaymentConfirmedPayload>('PaymentConfirmed', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'payment_confirmed', title: 'Enrollment confirmed', body: `You now have access to "${p.course_title}".`, link: `/learn/${p.course_id}` });
      this.deliver('PaymentConfirmed', p.learner_id, p.learner_email, 'Enrollment confirmed — receipt',
        layout('Payment received', `<p>Hi ${p.learner_name},</p><p>Your payment of <strong>${p.amount_etb} ETB</strong> for "${p.course_title}" is confirmed. Your course is unlocked — happy learning!</p><p>Reference: ${p.tx_ref}</p>`));
    });

    this.bus.subscribe<PaymentFailedPayload>('PaymentFailed', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'payment_failed', title: 'Payment could not be processed', body: `Your payment for "${p.course_title}" did not go through.`, link: `/courses/${p.course_id}` });
      this.deliver('PaymentFailed', p.learner_id, p.learner_email, 'Your payment could not be processed',
        layout('Payment failed', `<p>Your payment for "${p.course_title}" (${p.amount_etb} ETB) did not go through. No money was taken for this attempt — you can retry from the course page.</p>`));
    });

    this.bus.subscribe<EnrollmentCreatedPayload>('EnrollmentCreated', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'enrolled', title: `You're enrolled: ${p.course_title}`, body: `Start learning "${p.course_title}" from your dashboard.`, link: `/learn/${p.course_id}` });
      this.deliver('EnrollmentCreated', p.learner_id, p.learner_email, `You're enrolled: ${p.course_title}`,
        layout('Enrollment confirmed', `<p>Hi ${p.learner_name},</p><p>You're enrolled in "${p.course_title}"${p.educator_name ? ` by ${p.educator_name}` : ''}. Start learning from your dashboard.</p>`));
    });

    this.bus.subscribe<CertificateIssuedPayload>('CertificateIssued', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'certificate', title: 'Your certificate is ready 🎓', body: `You completed "${p.course_title}".`, link: '/dashboard' });
      this.deliver('CertificateIssued', p.learner_id, p.learner_email, 'Your certificate is ready',
        layout('Certificate issued 🎓', `<p>Congratulations ${p.learner_name}!</p><p>You completed "${p.course_title}". Your certificate is available in your dashboard, and anyone can verify it here:</p><p><a href="${p.verify_url}">${p.verify_url}</a></p>`));
    });

    this.bus.subscribe<PayoutPayload>('PayoutCompleted', (p) => {
      this.inbox({ user_id: p.payee_id, type: 'payout', title: 'Payout sent', body: `${p.net_amount_etb} ETB was disbursed to your account.`, link: '/teach' });
      if (p.payee_email) this.deliver('PayoutCompleted', p.payee_id, p.payee_email, 'Payout sent to your account',
        layout('Payout completed', `<p>Your payout of <strong>${p.net_amount_etb} ETB</strong> (gross ${p.gross_amount_etb} ETB − platform fee ${p.platform_fee_etb} ETB) has been disbursed.</p>`));
    });

    this.bus.subscribe<FraudFlagPayload>('FraudFlagRaised', (p) => {
      this.inbox({ role: Role.PLATFORM_ADMIN, type: 'fraud', title: 'Fraud flag raised', body: `${p.signal_type} on ${p.subject_type}. ${p.detail}`, link: '/admin' });
      this.deliver('FraudFlagRaised', null, this.adminEmail, 'Fraud flag raised — action needed',
        layout('Fraud flag raised', `<p>Signal <strong>${p.signal_type}</strong> on ${p.subject_type} <code>${p.subject_id}</code>.</p><p>${p.detail}</p><p>Payouts for the related payee are on hold until resolved in the admin console.</p>`));
    });

    this.bus.subscribe<FraudFlagPayload>('FraudFlagResolved', (p) =>
      this.deliver('FraudFlagResolved', null, this.adminEmail, 'Fraud flag resolved',
        layout('Fraud flag resolved', `<p>Flag <code>${p.flag_id}</code> (${p.signal_type}) has been resolved. Any payout holds have been released.</p>`)));

    // A refund needs an admin decision (manual-review band) → actionable admin inbox.
    this.bus.subscribe<RefundRequestedPayload>('RefundRequested', (p) => {
      this.inbox({ role: Role.PLATFORM_ADMIN, type: 'refund_request', title: 'Refund awaiting your decision', body: `${p.amount_etb} ETB refund requested for "${p.course_title}" (${p.reason}).`, link: '/admin' });
      this.deliver('RefundRequested', null, this.adminEmail, 'Refund request awaiting review',
        layout('Refund awaiting decision', `<p>A learner requested a ${p.amount_etb} ETB refund for "${p.course_title}".</p><p>Routing rule: <code>${p.reason}</code>. Approve or deny it in the admin console.</p>`));
    });

    this.bus.subscribe<RefundDecisionPayload>('RefundApproved', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'refund', title: 'Refund processed', body: `Your refund for "${p.course_title}" was approved.`, link: '/dashboard' });
      // Also record it in the admin inbox — many approvals are automatic (spec §10.4)
      // and never crossed an admin's desk, but they still move money.
      this.inbox({ role: Role.PLATFORM_ADMIN, type: 'refund', title: 'Refund approved', body: `${p.amount_etb} ETB refunded for "${p.course_title}".`, link: '/admin' });
      this.deliver('RefundApproved', p.learner_id, p.learner_email, 'Your refund has been processed',
        layout('Refund processed', `<p>Your refund of ${p.amount_etb} ETB for "${p.course_title}" was approved. Access to the course has been revoked.</p>`));
    });

    this.bus.subscribe<RefundDecisionPayload>('RefundDenied', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'refund', title: 'Refund request declined', body: `Your refund for "${p.course_title}" was declined (${p.reason}).`, link: '/dashboard' });
      this.deliver('RefundDenied', p.learner_id, p.learner_email, 'Refund request decision',
        layout('Refund request declined', `<p>Your refund request for "${p.course_title}" was declined (${p.reason}). Reply to this email if you believe this is a mistake.</p>`));
    });

    this.bus.subscribe<CourseCompletedPayload>('CourseCompleted', (p) =>
      this.deliver('CourseCompleted', p.learner_id, p.learner_email, `You finished ${p.course_title}!`,
        layout('Course completed', `<p>Well done ${p.learner_name} — you finished every lesson in "${p.course_title}".</p>`)));

    this.bus.subscribe<AssessmentResultPayload>('AssessmentFailed', (p) => {
      this.inbox({ user_id: p.learner_id, type: 'assessment', title: 'Assessment not passed', body: `Your ${p.assessment_type} for "${p.course_title}" scored ${p.score}.`, link: `/learn/${p.course_id}` });
      this.deliver('AssessmentFailed', p.learner_id, p.learner_email, 'Assessment result',
        layout('Assessment not passed', `<p>Your ${p.assessment_type} attempt for "${p.course_title}" scored ${p.score}. You can try again from the course page.</p>`));
    });

    this.bus.subscribe<CourseStatusPayload>('CourseUnlisted', (p) => {
      this.inbox({ user_id: p.owner_user_id, type: 'course_unlisted', title: 'Your course was unlisted', body: `"${p.title}" was removed from the catalog.`, link: `/teach/courses/${p.course_id}` });
      if (p.owner_email) this.deliver('CourseUnlisted', p.owner_user_id, p.owner_email, 'Your course was unlisted',
        layout('Course unlisted', `<p>"${p.title}" was temporarily removed from the catalog. You can re-publish it from your course page (or contact us if an admin unlisted it).</p>`));
    });
  }

  /**
   * When a course is published, notify every learner who follows its category
   * or its instructor — in-app and/or email, per each learner's preferences.
   * Best-effort: a failure for one recipient never blocks the others.
   */
  private async notifyNewCourseFollowers(p: CoursePublishedPayload) {
    let followers: NotificationPreference[];
    try {
      followers = await this.prefs
        .createQueryBuilder('pref')
        .where('(:category = ANY(pref.new_course_categories)) OR (:owner = ANY(pref.new_course_instructor_ids))', {
          category: p.category,
          owner: p.owner_user_id,
        })
        .limit(2000) // safety cap; batch/queue this if follower counts ever get huge
        .getMany();
    } catch (err) {
      this.logger.warn(`new-course fan-out query failed for ${p.course_id}: ${(err as Error).message}`);
      return;
    }
    // Don't notify the instructor about their own course (they get the owner ping).
    followers = followers.filter((f) => f.user_id !== p.owner_user_id);
    if (followers.length === 0) return;

    const instructorName = await this.userName(p.owner_user_id);
    const categoryLabel = courseCategoryLabel(p.category);
    const link = `/courses/${p.course_id}`;
    this.logger.log(`CoursePublished "${p.title}" → notifying ${followers.length} follower(s)`);

    for (const f of followers) {
      const followsInstructor = (f.new_course_instructor_ids ?? []).includes(p.owner_user_id);
      const reason = followsInstructor ? `${instructorName} just published a new course` : `New ${categoryLabel} course`;
      if (f.new_course_in_app !== false) {
        await this.inbox({ user_id: f.user_id, type: 'new_course', title: reason, body: `"${p.title}" is now available. Tap to explore.`, link });
      }
      if (f.new_course_email !== false) {
        const user = await this.userInfo(f.user_id);
        if (!user.email) continue;
        await this.deliver('NewCourseAlert', f.user_id, user.email, `${reason}: ${p.title}`,
          layout(reason, `<p>Hi ${user.name || 'there'},</p>
          <p>${followsInstructor ? `<strong>${instructorName}</strong> just published` : `A new <strong>${categoryLabel}</strong> course just dropped`} on EthiopiaLearn:</p>
          <p style="font-size:16px"><strong>${p.title}</strong></p>
          <p><a href="${this.webUrl}${link}" style="background:#0f766e;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">View the course</a></p>
          <p style="color:#6b7280;font-size:12px;margin-top:16px">You're getting this because you follow ${followsInstructor ? 'this instructor' : `the ${categoryLabel} category`}. Manage alerts in your account settings.</p>`));
      }
    }
  }

  private async userInfo(userId: string): Promise<{ email: string; name: string }> {
    try {
      return await this.internal.get<{ email: string; name: string }>(`/api/v1/internal/users/${userId}`);
    } catch {
      return { email: '', name: '' };
    }
  }

  private async userName(userId: string): Promise<string> {
    return (await this.userInfo(userId)).name || 'An instructor you follow';
  }

  private async inbox(input: InboxInput) {
    if (!input.user_id && !input.role) return;
    try {
      await this.inboxRepo.save(
        this.inboxRepo.create({
          user_id: input.user_id ?? null,
          target_role: input.role ?? null,
          type: input.type,
          title: input.title,
          body: input.body ?? '',
          link: input.link ?? null,
          read_at: null,
        }),
      );
    } catch (err) {
      this.logger.warn(`inbox write failed (${input.type}): ${(err as Error).message}`);
    }
  }

  private async deliver(eventType: string, userId: string | null, to: string, subject: string, html: string) {
    if (!to) {
      this.logger.warn(`skipping ${eventType}: no recipient`);
      return;
    }
    try {
      const { message_id } = await this.email.send({ to, subject, html });
      await this.log.save(
        this.log.create({ user_id: userId, event_type: eventType, channel: 'email', recipient: to, subject, status: 'sent', provider_message_id: message_id }),
      );
      await this.bus.publish('NotificationSent', { user_id: userId, event_type: eventType, channel: 'email' });
    } catch (err) {
      this.logger.error(`email failed for ${eventType} -> ${to}: ${(err as Error).message}`);
      await this.log.save(
        this.log.create({ user_id: userId, event_type: eventType, channel: 'email', recipient: to, subject, status: 'failed', provider_message_id: null }),
      );
    }
  }
}
